# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('ngrok')


class _ExportableConfig(types.ModuleType):
    @property
    def api_base_url(self) -> Optional[str]:
        """
        base URL for the ngrok API. only overridden for ngrok's internal testing purposes.
        """
        return __config__.get('apiBaseUrl')

    @property
    def api_key(self) -> Optional[str]:
        """
        ngrok API key used for authenticating to the API
        """
        return __config__.get('apiKey')

