// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok
{
    /// <summary>
    /// Reserved Addresses are TCP addresses that can be used to listen for traffic.
    ///  TCP address hostnames and ports are assigned by ngrok, they cannot be
    ///  chosen.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Ngrok = PiersKarsenbarg.Ngrok;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Ngrok.ReservedAddress("example", new()
    ///     {
    ///         Description = "SSH for device #001",
    ///         Region = "us",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [NgrokResourceType("ngrok:index/reservedAddress:ReservedAddress")]
    public partial class ReservedAddress : global::Pulumi.CustomResource
    {
        /// <summary>
        /// hostname:port of the reserved address that was assigned at creation time
        /// </summary>
        [Output("addr")]
        public Output<string> Addr { get; private set; } = null!;

        /// <summary>
        /// human-readable description of what this reserved address will be used for
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// ID of an endpoint configuration of type tcp that will be used to handle inbound traffic to this address
        /// </summary>
        [Output("endpointConfigurationId")]
        public Output<string?> EndpointConfigurationId { get; private set; } = null!;

        /// <summary>
        /// arbitrary user-defined machine-readable data of this reserved address. Optional, max 4096 bytes.
        /// </summary>
        [Output("metadata")]
        public Output<string?> Metadata { get; private set; } = null!;

        /// <summary>
        /// reserve the address in this geographic ngrok datacenter. Optional, default is us. (au, eu, ap, us, jp, in, sa)
        /// </summary>
        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;


        /// <summary>
        /// Create a ReservedAddress resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ReservedAddress(string name, ReservedAddressArgs? args = null, CustomResourceOptions? options = null)
            : base("ngrok:index/reservedAddress:ReservedAddress", name, args ?? new ReservedAddressArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ReservedAddress(string name, Input<string> id, ReservedAddressState? state = null, CustomResourceOptions? options = null)
            : base("ngrok:index/reservedAddress:ReservedAddress", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pierskarsenbarg/pulumi-ngrok",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ReservedAddress resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ReservedAddress Get(string name, Input<string> id, ReservedAddressState? state = null, CustomResourceOptions? options = null)
        {
            return new ReservedAddress(name, id, state, options);
        }
    }

    public sealed class ReservedAddressArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// hostname:port of the reserved address that was assigned at creation time
        /// </summary>
        [Input("addr")]
        public Input<string>? Addr { get; set; }

        /// <summary>
        /// human-readable description of what this reserved address will be used for
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// ID of an endpoint configuration of type tcp that will be used to handle inbound traffic to this address
        /// </summary>
        [Input("endpointConfigurationId")]
        public Input<string>? EndpointConfigurationId { get; set; }

        /// <summary>
        /// arbitrary user-defined machine-readable data of this reserved address. Optional, max 4096 bytes.
        /// </summary>
        [Input("metadata")]
        public Input<string>? Metadata { get; set; }

        /// <summary>
        /// reserve the address in this geographic ngrok datacenter. Optional, default is us. (au, eu, ap, us, jp, in, sa)
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        public ReservedAddressArgs()
        {
        }
        public static new ReservedAddressArgs Empty => new ReservedAddressArgs();
    }

    public sealed class ReservedAddressState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// hostname:port of the reserved address that was assigned at creation time
        /// </summary>
        [Input("addr")]
        public Input<string>? Addr { get; set; }

        /// <summary>
        /// human-readable description of what this reserved address will be used for
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// ID of an endpoint configuration of type tcp that will be used to handle inbound traffic to this address
        /// </summary>
        [Input("endpointConfigurationId")]
        public Input<string>? EndpointConfigurationId { get; set; }

        /// <summary>
        /// arbitrary user-defined machine-readable data of this reserved address. Optional, max 4096 bytes.
        /// </summary>
        [Input("metadata")]
        public Input<string>? Metadata { get; set; }

        /// <summary>
        /// reserve the address in this geographic ngrok datacenter. Optional, default is us. (au, eu, ap, us, jp, in, sa)
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        public ReservedAddressState()
        {
        }
        public static new ReservedAddressState Empty => new ReservedAddressState();
    }
}
