// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EndpointConfigurationResponseHeader
    {
        /// <summary>
        /// a map of header key to header value that will be injected into the HTTP Response returned to the HTTP client
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Add;
        /// <summary>
        /// `true` if the module will be applied to traffic, `false` to disable. default `true` if unspecified
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// a list of header names that will be removed from the HTTP Response returned to the HTTP client
        /// </summary>
        public readonly ImmutableArray<string> Removes;

        [OutputConstructor]
        private EndpointConfigurationResponseHeader(
            ImmutableDictionary<string, string>? add,

            bool? enabled,

            ImmutableArray<string> removes)
        {
            Add = add;
            Enabled = enabled;
            Removes = removes;
        }
    }
}
