// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EndpointConfigurationWebhookValidation
    {
        /// <summary>
        /// `true` if the module will be applied to traffic, `false` to disable. default `true` if unspecified
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// a string indicating which webhook provider will be sending webhooks to this endpoint. Value must be one of the supported providers: `SLACK`, `SNS`, `STRIPE`, `GITHUB`, `TWILIO`, `SHOPIFY`, `GITLAB`, `INTERCOM`, `SENDGRID`, `XERO`, `PAGERDUTY`.
        /// </summary>
        public readonly string? Provider;
        /// <summary>
        /// a string secret used to validate requests from the given provider. All providers except AWS SNS require a secret
        /// </summary>
        public readonly string? Secret;

        [OutputConstructor]
        private EndpointConfigurationWebhookValidation(
            bool? enabled,

            string? provider,

            string? secret)
        {
            Enabled = enabled;
            Provider = provider;
            Secret = secret;
        }
    }
}
