// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EndpointConfigurationMutualTl
    {
        /// <summary>
        /// PEM-encoded CA certificates that will be used to validate. Multiple CAs may be provided by concatenating them together.
        /// </summary>
        public readonly ImmutableArray<Outputs.EndpointConfigurationMutualTlCertificateAuthority> CertificateAuthorities;
        /// <summary>
        /// `true` if the module will be applied to traffic, `false` to disable. default `true` if unspecified
        /// </summary>
        public readonly bool? Enabled;

        [OutputConstructor]
        private EndpointConfigurationMutualTl(
            ImmutableArray<Outputs.EndpointConfigurationMutualTlCertificateAuthority> certificateAuthorities,

            bool? enabled)
        {
            CertificateAuthorities = certificateAuthorities;
            Enabled = enabled;
        }
    }
}
