// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EndpointConfigurationOauthProviderFacebook
    {
        /// <summary>
        /// the OAuth app client ID. retrieve it from the identity provider's dashboard where you created your own OAuth app. optional. if unspecified, ngrok will use its own managed oauth application which has additional restrictions. see the OAuth module docs for more details. if present, client_secret must be present as well.
        /// </summary>
        public readonly string? ClientId;
        /// <summary>
        /// the OAuth app client secret. retrieve if from the identity provider's dashboard where you created your own OAuth app. optional, see all of the caveats in the docs for `client_id`.
        /// </summary>
        public readonly string? ClientSecret;
        /// <summary>
        /// a list of email addresses of users authenticated by identity provider who are allowed access to the endpoint
        /// </summary>
        public readonly ImmutableArray<string> EmailAddresses;
        /// <summary>
        /// a list of email domains of users authenticated by identity provider who are allowed access to the endpoint
        /// </summary>
        public readonly ImmutableArray<string> EmailDomains;
        /// <summary>
        /// a list of provider-specific OAuth scopes with the permissions your OAuth app would like to ask for. these may not be set if you are using the ngrok-managed oauth app (i.e. you must pass both `client_id` and `client_secret` to set scopes)
        /// </summary>
        public readonly ImmutableArray<string> Scopes;

        [OutputConstructor]
        private EndpointConfigurationOauthProviderFacebook(
            string? clientId,

            string? clientSecret,

            ImmutableArray<string> emailAddresses,

            ImmutableArray<string> emailDomains,

            ImmutableArray<string> scopes)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            EmailAddresses = emailAddresses;
            EmailDomains = emailDomains;
            Scopes = scopes;
        }
    }
}
