// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EndpointConfigurationOauthProvider
    {
        /// <summary>
        /// configuration for using facebook as the identity provider
        /// </summary>
        public readonly ImmutableArray<Outputs.EndpointConfigurationOauthProviderFacebook> Facebooks;
        /// <summary>
        /// configuration for using github as the identity provider
        /// </summary>
        public readonly ImmutableArray<Outputs.EndpointConfigurationOauthProviderGithub> Githubs;
        /// <summary>
        /// configuration for using google as the identity provider
        /// </summary>
        public readonly ImmutableArray<Outputs.EndpointConfigurationOauthProviderGoogle> Googles;
        /// <summary>
        /// configuration for using microsoft as the identity provider
        /// </summary>
        public readonly ImmutableArray<Outputs.EndpointConfigurationOauthProviderMicrosoft> Microsofts;

        [OutputConstructor]
        private EndpointConfigurationOauthProvider(
            ImmutableArray<Outputs.EndpointConfigurationOauthProviderFacebook> facebooks,

            ImmutableArray<Outputs.EndpointConfigurationOauthProviderGithub> githubs,

            ImmutableArray<Outputs.EndpointConfigurationOauthProviderGoogle> googles,

            ImmutableArray<Outputs.EndpointConfigurationOauthProviderMicrosoft> microsofts)
        {
            Facebooks = facebooks;
            Githubs = githubs;
            Googles = googles;
            Microsofts = microsofts;
        }
    }
}
