// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EndpointConfigurationOauth
    {
        /// <summary>
        /// Integer number of seconds after which ngrok guarantees it will refresh user state from the identity provider and recheck whether the user is still authorized to access the endpoint. This is the preferred tunable to use to enforce a minimum amount of time after which a revoked user will no longer be able to access the resource.
        /// </summary>
        public readonly int? AuthCheckInterval;
        /// <summary>
        /// the prefix of the session cookie that ngrok sets on the http client to cache authentication. default is 'ngrok.'
        /// </summary>
        public readonly string? CookiePrefix;
        /// <summary>
        /// `true` if the module will be applied to traffic, `false` to disable. default `true` if unspecified
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Integer number of seconds of inactivity after which if the user has not accessed the endpoint, their session will time out and they will be forced to reauthenticate.
        /// </summary>
        public readonly int? InactivityTimeout;
        /// <summary>
        /// Integer number of seconds of the maximum duration of an authenticated session. After this period is exceeded, a user must reauthenticate.
        /// </summary>
        public readonly int? MaximumDuration;
        /// <summary>
        /// Do not enforce authentication on HTTP OPTIONS requests. necessary if you are supporting CORS.
        /// </summary>
        public readonly bool? OptionsPassthrough;
        /// <summary>
        /// an object which defines the identity provider to use for authentication and configuration for who may access the endpoint
        /// </summary>
        public readonly ImmutableArray<Outputs.EndpointConfigurationOauthProvider> Providers;

        [OutputConstructor]
        private EndpointConfigurationOauth(
            int? authCheckInterval,

            string? cookiePrefix,

            bool? enabled,

            int? inactivityTimeout,

            int? maximumDuration,

            bool? optionsPassthrough,

            ImmutableArray<Outputs.EndpointConfigurationOauthProvider> providers)
        {
            AuthCheckInterval = authCheckInterval;
            CookiePrefix = cookiePrefix;
            Enabled = enabled;
            InactivityTimeout = inactivityTimeout;
            MaximumDuration = maximumDuration;
            OptionsPassthrough = optionsPassthrough;
            Providers = providers;
        }
    }
}
