// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EventDestinationTargetKinese
    {
        public readonly ImmutableArray<Outputs.EventDestinationTargetKineseAuth> Auths;
        public readonly string? StreamArn;

        [OutputConstructor]
        private EventDestinationTargetKinese(
            ImmutableArray<Outputs.EventDestinationTargetKineseAuth> auths,

            string? streamArn)
        {
            Auths = auths;
            StreamArn = streamArn;
        }
    }
}
