// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EventDestinationTargetDebug
    {
        /// <summary>
        /// URL to send events to.
        /// </summary>
        public readonly string? CallbackUrl;
        /// <summary>
        /// Whether or not to output to publisher service logs.
        /// </summary>
        public readonly bool? Log;

        [OutputConstructor]
        private EventDestinationTargetDebug(
            string? callbackUrl,

            bool? log)
        {
            CallbackUrl = callbackUrl;
            Log = log;
        }
    }
}
