// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EventDestinationTargetKineseAuth
    {
        /// <summary>
        /// Credentials to your AWS account if you prefer ngrok to sign in with long-term access keys.
        /// </summary>
        public readonly ImmutableArray<Outputs.EventDestinationTargetKineseAuthCred> Creds;
        /// <summary>
        /// A role for ngrok to assume on your behalf to deposit events into your AWS account.
        /// </summary>
        public readonly ImmutableArray<Outputs.EventDestinationTargetKineseAuthRole> Roles;

        [OutputConstructor]
        private EventDestinationTargetKineseAuth(
            ImmutableArray<Outputs.EventDestinationTargetKineseAuthCred> creds,

            ImmutableArray<Outputs.EventDestinationTargetKineseAuthRole> roles)
        {
            Creds = creds;
            Roles = roles;
        }
    }
}
