// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Outputs
{

    [OutputType]
    public sealed class EventDestinationTargetFirehose
    {
        public readonly ImmutableArray<Outputs.EventDestinationTargetFirehoseAuth> Auths;
        public readonly string? DeliveryStreamArn;

        [OutputConstructor]
        private EventDestinationTargetFirehose(
            ImmutableArray<Outputs.EventDestinationTargetFirehoseAuth> auths,

            string? deliveryStreamArn)
        {
            Auths = auths;
            DeliveryStreamArn = deliveryStreamArn;
        }
    }
}
