# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .agent_ingress import *
from .api_key import *
from .certificate_authority import *
from .credential import *
from .endpoint_configuration import *
from .event_destination import *
from .event_subscription import *
from .ip_policy import *
from .ip_policy_rule import *
from .ip_restriction import *
from .provider import *
from .reserved_address import *
from .reserved_domain import *
from .ssh_certificate_authority import *
from .ssh_credential import *
from .ssh_host_certificate import *
from .ssh_user_certificate import *
from .tls_certificate import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pierskarsenbarg_pulumi_ngrok.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pierskarsenbarg_pulumi_ngrok.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ngrok",
  "mod": "index/agentIngress",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/agentIngress:AgentIngress": "AgentIngress"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/apiKey",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/apiKey:ApiKey": "ApiKey"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/certificateAuthority",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/certificateAuthority:CertificateAuthority": "CertificateAuthority"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/credential",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/credential:Credential": "Credential"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/endpointConfiguration",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/endpointConfiguration:EndpointConfiguration": "EndpointConfiguration"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/eventDestination",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/eventDestination:EventDestination": "EventDestination"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/eventSubscription",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/eventSubscription:EventSubscription": "EventSubscription"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/ipPolicy",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/ipPolicy:IpPolicy": "IpPolicy"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/ipPolicyRule",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/ipPolicyRule:IpPolicyRule": "IpPolicyRule"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/ipRestriction",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/ipRestriction:IpRestriction": "IpRestriction"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/reservedAddress",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/reservedAddress:ReservedAddress": "ReservedAddress"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/reservedDomain",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/reservedDomain:ReservedDomain": "ReservedDomain"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/sshCertificateAuthority",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/sshCertificateAuthority:SshCertificateAuthority": "SshCertificateAuthority"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/sshCredential",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/sshCredential:SshCredential": "SshCredential"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/sshHostCertificate",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/sshHostCertificate:SshHostCertificate": "SshHostCertificate"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/sshUserCertificate",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/sshUserCertificate:SshUserCertificate": "SshUserCertificate"
  }
 },
 {
  "pkg": "ngrok",
  "mod": "index/tlsCertificate",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "classes": {
   "ngrok:index/tlsCertificate:TlsCertificate": "TlsCertificate"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ngrok",
  "token": "pulumi:providers:ngrok",
  "fqn": "pierskarsenbarg_pulumi_ngrok",
  "class": "Provider"
 }
]
"""
)
