// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Inputs
{

    public sealed class EventDestinationTargetGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("cloudwatchLogs")]
        private InputList<Inputs.EventDestinationTargetCloudwatchLogGetArgs>? _cloudwatchLogs;

        /// <summary>
        /// Configuration used to send events to Amazon CloudWatch Logs.
        /// </summary>
        public InputList<Inputs.EventDestinationTargetCloudwatchLogGetArgs> CloudwatchLogs
        {
            get => _cloudwatchLogs ?? (_cloudwatchLogs = new InputList<Inputs.EventDestinationTargetCloudwatchLogGetArgs>());
            set => _cloudwatchLogs = value;
        }

        [Input("debugs")]
        private InputList<Inputs.EventDestinationTargetDebugGetArgs>? _debugs;

        /// <summary>
        /// Configuration used for internal debugging.
        /// </summary>
        public InputList<Inputs.EventDestinationTargetDebugGetArgs> Debugs
        {
            get => _debugs ?? (_debugs = new InputList<Inputs.EventDestinationTargetDebugGetArgs>());
            set => _debugs = value;
        }

        [Input("firehoses")]
        private InputList<Inputs.EventDestinationTargetFirehoseGetArgs>? _firehoses;

        /// <summary>
        /// Configuration used to send events to Amazon Kinesis Data Firehose.
        /// </summary>
        public InputList<Inputs.EventDestinationTargetFirehoseGetArgs> Firehoses
        {
            get => _firehoses ?? (_firehoses = new InputList<Inputs.EventDestinationTargetFirehoseGetArgs>());
            set => _firehoses = value;
        }

        [Input("kineses")]
        private InputList<Inputs.EventDestinationTargetKineseGetArgs>? _kineses;

        /// <summary>
        /// Configuration used to send events to Amazon Kinesis.
        /// </summary>
        public InputList<Inputs.EventDestinationTargetKineseGetArgs> Kineses
        {
            get => _kineses ?? (_kineses = new InputList<Inputs.EventDestinationTargetKineseGetArgs>());
            set => _kineses = value;
        }

        public EventDestinationTargetGetArgs()
        {
        }
        public static new EventDestinationTargetGetArgs Empty => new EventDestinationTargetGetArgs();
    }
}
