// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Inputs
{

    public sealed class EventDestinationTargetFirehoseAuthGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("creds")]
        private InputList<Inputs.EventDestinationTargetFirehoseAuthCredGetArgs>? _creds;
        public InputList<Inputs.EventDestinationTargetFirehoseAuthCredGetArgs> Creds
        {
            get => _creds ?? (_creds = new InputList<Inputs.EventDestinationTargetFirehoseAuthCredGetArgs>());
            set => _creds = value;
        }

        [Input("roles")]
        private InputList<Inputs.EventDestinationTargetFirehoseAuthRoleGetArgs>? _roles;
        public InputList<Inputs.EventDestinationTargetFirehoseAuthRoleGetArgs> Roles
        {
            get => _roles ?? (_roles = new InputList<Inputs.EventDestinationTargetFirehoseAuthRoleGetArgs>());
            set => _roles = value;
        }

        public EventDestinationTargetFirehoseAuthGetArgs()
        {
        }
        public static new EventDestinationTargetFirehoseAuthGetArgs Empty => new EventDestinationTargetFirehoseAuthGetArgs();
    }
}
