// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Inputs
{

    public sealed class EventDestinationTargetFirehoseAuthRoleGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An ARN that specifies the role that ngrok should use to deliver to the configured target.
        /// </summary>
        [Input("roleArn", required: true)]
        public Input<string> RoleArn { get; set; } = null!;

        public EventDestinationTargetFirehoseAuthRoleGetArgs()
        {
        }
        public static new EventDestinationTargetFirehoseAuthRoleGetArgs Empty => new EventDestinationTargetFirehoseAuthRoleGetArgs();
    }
}
