// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Inputs
{

    public sealed class EventDestinationTargetFirehoseAuthArgs : global::Pulumi.ResourceArgs
    {
        [Input("creds")]
        private InputList<Inputs.EventDestinationTargetFirehoseAuthCredArgs>? _creds;
        public InputList<Inputs.EventDestinationTargetFirehoseAuthCredArgs> Creds
        {
            get => _creds ?? (_creds = new InputList<Inputs.EventDestinationTargetFirehoseAuthCredArgs>());
            set => _creds = value;
        }

        [Input("roles")]
        private InputList<Inputs.EventDestinationTargetFirehoseAuthRoleArgs>? _roles;
        public InputList<Inputs.EventDestinationTargetFirehoseAuthRoleArgs> Roles
        {
            get => _roles ?? (_roles = new InputList<Inputs.EventDestinationTargetFirehoseAuthRoleArgs>());
            set => _roles = value;
        }

        public EventDestinationTargetFirehoseAuthArgs()
        {
        }
        public static new EventDestinationTargetFirehoseAuthArgs Empty => new EventDestinationTargetFirehoseAuthArgs();
    }
}
