// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Inputs
{

    public sealed class EventDestinationTargetFirehoseArgs : global::Pulumi.ResourceArgs
    {
        [Input("auths")]
        private InputList<Inputs.EventDestinationTargetFirehoseAuthArgs>? _auths;
        public InputList<Inputs.EventDestinationTargetFirehoseAuthArgs> Auths
        {
            get => _auths ?? (_auths = new InputList<Inputs.EventDestinationTargetFirehoseAuthArgs>());
            set => _auths = value;
        }

        [Input("deliveryStreamArn")]
        public Input<string>? DeliveryStreamArn { get; set; }

        public EventDestinationTargetFirehoseArgs()
        {
        }
        public static new EventDestinationTargetFirehoseArgs Empty => new EventDestinationTargetFirehoseArgs();
    }
}
