// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Ngrok.Inputs
{

    public sealed class EventDestinationTargetFirehoseAuthCredGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("awsAccessKeyId", required: true)]
        public Input<string> AwsAccessKeyId { get; set; } = null!;

        [Input("awsSecretAccessKey", required: true)]
        public Input<string> AwsSecretAccessKey { get; set; } = null!;

        public EventDestinationTargetFirehoseAuthCredGetArgs()
        {
        }
        public static new EventDestinationTargetFirehoseAuthCredGetArgs Empty => new EventDestinationTargetFirehoseAuthCredGetArgs();
    }
}
