env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  # NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PROVIDER: ngrok
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_API: https://api.pulumi.com
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PULUMI_TEST_OWNER: "pierskarsenbarg"
  NGROK_API_KEY: ${{secrets.NGROK_API_KEY}}
  # PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  # PYPI_USERNAME: "__token__"
  # SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
  # SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
  # SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
  # TRAVIS_OS_NAME: linux
jobs:
  comment-on-pr:
    if: github.event.pull_request.head.repo.full_name != github.repository
    name: comment-on-pr
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@1.0.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          PR is now waiting for a maintainer to run the acceptance tests.
          **Note for the maintainer:** To run the acceptance tests, please comment */run-acceptance-tests* on the PR
    strategy: {}
name: pull-request
"on":
  pull_request_target: {}