// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Endpoint Configurations are a reusable group of modules that encapsulate how
 *  traffic to a domain or address is handled. Endpoint configurations are only
 *  applied to Domains and TCP Addresses they have been attached to.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ngrok from "@pierskarsenbarg/ngrok";
 *
 * const example = new ngrok.EndpointConfiguration("example", {
 *     description: "app servers",
 *     requestHeaders: [{
 *         add: {
 *             "x-frontend": "ngrok",
 *         },
 *         removes: ["cache-control"],
 *     }],
 *     type: "https",
 * });
 * ```
 */
export class EndpointConfiguration extends pulumi.CustomResource {
    /**
     * Get an existing EndpointConfiguration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EndpointConfigurationState, opts?: pulumi.CustomResourceOptions): EndpointConfiguration {
        return new EndpointConfiguration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ngrok:index/endpointConfiguration:EndpointConfiguration';

    /**
     * Returns true if the given object is an instance of EndpointConfiguration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EndpointConfiguration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EndpointConfiguration.__pulumiType;
    }

    /**
     * backend module configuration or `null`
     */
    public readonly backends!: pulumi.Output<outputs.EndpointConfigurationBackend[] | undefined>;
    /**
     * basic auth module configuration or `null`
     */
    public readonly basicAuths!: pulumi.Output<outputs.EndpointConfigurationBasicAuth[] | undefined>;
    /**
     * circuit breaker module configuration or `null`
     */
    public readonly circuitBreakers!: pulumi.Output<outputs.EndpointConfigurationCircuitBreaker[] | undefined>;
    /**
     * compression module configuration or `null`
     */
    public readonly compressions!: pulumi.Output<outputs.EndpointConfigurationCompression[] | undefined>;
    /**
     * human-readable description of what this endpoint configuration will be do when applied or what traffic it will be applied to. Optional, max 255 bytes
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * ip policy module configuration or `null`
     */
    public readonly ipPolicies!: pulumi.Output<outputs.EndpointConfigurationIpPolicy[] | undefined>;
    /**
     * logging module configuration or `null`
     */
    public readonly loggings!: pulumi.Output<outputs.EndpointConfigurationLogging[] | undefined>;
    /**
     * arbitrary user-defined machine-readable data of this endpoint configuration. Optional, max 4096 bytes.
     */
    public readonly metadata!: pulumi.Output<string | undefined>;
    /**
     * mutual TLS module configuration or `null`
     */
    public readonly mutualTls!: pulumi.Output<outputs.EndpointConfigurationMutualTl[] | undefined>;
    /**
     * oauth module configuration or `null`
     */
    public readonly oauths!: pulumi.Output<outputs.EndpointConfigurationOauth[] | undefined>;
    /**
     * oidc module configuration or `null`
     */
    public readonly oidcs!: pulumi.Output<outputs.EndpointConfigurationOidc[] | undefined>;
    /**
     * request headers module configuration or `null`
     */
    public readonly requestHeaders!: pulumi.Output<outputs.EndpointConfigurationRequestHeader[] | undefined>;
    /**
     * response headers module configuration or `null`
     */
    public readonly responseHeaders!: pulumi.Output<outputs.EndpointConfigurationResponseHeader[] | undefined>;
    /**
     * saml module configuration or `null`
     */
    public readonly samls!: pulumi.Output<outputs.EndpointConfigurationSaml[] | undefined>;
    /**
     * TLS termination module configuration or `null`
     */
    public readonly tlsTerminations!: pulumi.Output<outputs.EndpointConfigurationTlsTermination[] | undefined>;
    /**
     * they type of traffic this endpoint configuration can be applied to. one of: `http`, `https`, `tcp`
     */
    public readonly type!: pulumi.Output<string | undefined>;
    /**
     * webhook validation module configuration or `null`
     */
    public readonly webhookValidations!: pulumi.Output<outputs.EndpointConfigurationWebhookValidation[] | undefined>;

    /**
     * Create a EndpointConfiguration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: EndpointConfigurationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EndpointConfigurationArgs | EndpointConfigurationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EndpointConfigurationState | undefined;
            resourceInputs["backends"] = state ? state.backends : undefined;
            resourceInputs["basicAuths"] = state ? state.basicAuths : undefined;
            resourceInputs["circuitBreakers"] = state ? state.circuitBreakers : undefined;
            resourceInputs["compressions"] = state ? state.compressions : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["ipPolicies"] = state ? state.ipPolicies : undefined;
            resourceInputs["loggings"] = state ? state.loggings : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["mutualTls"] = state ? state.mutualTls : undefined;
            resourceInputs["oauths"] = state ? state.oauths : undefined;
            resourceInputs["oidcs"] = state ? state.oidcs : undefined;
            resourceInputs["requestHeaders"] = state ? state.requestHeaders : undefined;
            resourceInputs["responseHeaders"] = state ? state.responseHeaders : undefined;
            resourceInputs["samls"] = state ? state.samls : undefined;
            resourceInputs["tlsTerminations"] = state ? state.tlsTerminations : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["webhookValidations"] = state ? state.webhookValidations : undefined;
        } else {
            const args = argsOrState as EndpointConfigurationArgs | undefined;
            resourceInputs["backends"] = args ? args.backends : undefined;
            resourceInputs["basicAuths"] = args ? args.basicAuths : undefined;
            resourceInputs["circuitBreakers"] = args ? args.circuitBreakers : undefined;
            resourceInputs["compressions"] = args ? args.compressions : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["ipPolicies"] = args ? args.ipPolicies : undefined;
            resourceInputs["loggings"] = args ? args.loggings : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["mutualTls"] = args ? args.mutualTls : undefined;
            resourceInputs["oauths"] = args ? args.oauths : undefined;
            resourceInputs["oidcs"] = args ? args.oidcs : undefined;
            resourceInputs["requestHeaders"] = args ? args.requestHeaders : undefined;
            resourceInputs["responseHeaders"] = args ? args.responseHeaders : undefined;
            resourceInputs["samls"] = args ? args.samls : undefined;
            resourceInputs["tlsTerminations"] = args ? args.tlsTerminations : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["webhookValidations"] = args ? args.webhookValidations : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EndpointConfiguration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EndpointConfiguration resources.
 */
export interface EndpointConfigurationState {
    /**
     * backend module configuration or `null`
     */
    backends?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationBackend>[]>;
    /**
     * basic auth module configuration or `null`
     */
    basicAuths?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationBasicAuth>[]>;
    /**
     * circuit breaker module configuration or `null`
     */
    circuitBreakers?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationCircuitBreaker>[]>;
    /**
     * compression module configuration or `null`
     */
    compressions?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationCompression>[]>;
    /**
     * human-readable description of what this endpoint configuration will be do when applied or what traffic it will be applied to. Optional, max 255 bytes
     */
    description?: pulumi.Input<string>;
    /**
     * ip policy module configuration or `null`
     */
    ipPolicies?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationIpPolicy>[]>;
    /**
     * logging module configuration or `null`
     */
    loggings?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationLogging>[]>;
    /**
     * arbitrary user-defined machine-readable data of this endpoint configuration. Optional, max 4096 bytes.
     */
    metadata?: pulumi.Input<string>;
    /**
     * mutual TLS module configuration or `null`
     */
    mutualTls?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationMutualTl>[]>;
    /**
     * oauth module configuration or `null`
     */
    oauths?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationOauth>[]>;
    /**
     * oidc module configuration or `null`
     */
    oidcs?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationOidc>[]>;
    /**
     * request headers module configuration or `null`
     */
    requestHeaders?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationRequestHeader>[]>;
    /**
     * response headers module configuration or `null`
     */
    responseHeaders?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationResponseHeader>[]>;
    /**
     * saml module configuration or `null`
     */
    samls?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationSaml>[]>;
    /**
     * TLS termination module configuration or `null`
     */
    tlsTerminations?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationTlsTermination>[]>;
    /**
     * they type of traffic this endpoint configuration can be applied to. one of: `http`, `https`, `tcp`
     */
    type?: pulumi.Input<string>;
    /**
     * webhook validation module configuration or `null`
     */
    webhookValidations?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationWebhookValidation>[]>;
}

/**
 * The set of arguments for constructing a EndpointConfiguration resource.
 */
export interface EndpointConfigurationArgs {
    /**
     * backend module configuration or `null`
     */
    backends?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationBackend>[]>;
    /**
     * basic auth module configuration or `null`
     */
    basicAuths?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationBasicAuth>[]>;
    /**
     * circuit breaker module configuration or `null`
     */
    circuitBreakers?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationCircuitBreaker>[]>;
    /**
     * compression module configuration or `null`
     */
    compressions?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationCompression>[]>;
    /**
     * human-readable description of what this endpoint configuration will be do when applied or what traffic it will be applied to. Optional, max 255 bytes
     */
    description?: pulumi.Input<string>;
    /**
     * ip policy module configuration or `null`
     */
    ipPolicies?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationIpPolicy>[]>;
    /**
     * logging module configuration or `null`
     */
    loggings?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationLogging>[]>;
    /**
     * arbitrary user-defined machine-readable data of this endpoint configuration. Optional, max 4096 bytes.
     */
    metadata?: pulumi.Input<string>;
    /**
     * mutual TLS module configuration or `null`
     */
    mutualTls?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationMutualTl>[]>;
    /**
     * oauth module configuration or `null`
     */
    oauths?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationOauth>[]>;
    /**
     * oidc module configuration or `null`
     */
    oidcs?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationOidc>[]>;
    /**
     * request headers module configuration or `null`
     */
    requestHeaders?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationRequestHeader>[]>;
    /**
     * response headers module configuration or `null`
     */
    responseHeaders?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationResponseHeader>[]>;
    /**
     * saml module configuration or `null`
     */
    samls?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationSaml>[]>;
    /**
     * TLS termination module configuration or `null`
     */
    tlsTerminations?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationTlsTermination>[]>;
    /**
     * they type of traffic this endpoint configuration can be applied to. one of: `http`, `https`, `tcp`
     */
    type?: pulumi.Input<string>;
    /**
     * webhook validation module configuration or `null`
     */
    webhookValidations?: pulumi.Input<pulumi.Input<inputs.EndpointConfigurationWebhookValidation>[]>;
}
